export const MainActionsTypes = {
    FETCH_USER: 'FETCH_USER',
    SETTITLE: 'SETTITLE',
    FIRE_SNACK: 'FIRE_SNACK',
    CLOSE_SNACK: 'CLOSE_SNACK',
    TOGGLE_DRAWER: 'TOGGLE_DRAWER',
    REDIRECT: 'REDIRECT'
}